//Falco run-time Container Threat Detection: Secrets extracted with kubctl (read Kubernets secrets)
//cryptsus.com - We craft Cyber Security Solutions
FalcoContainerSecurity
| where Activity == "The docker client is executed in a container"
| where cmdline contains_cs "kubectl get secrets"
| project-away TenantId, DeviceVendor, DeviceProduct, DeviceVersion, DeviceEventClassID, Message, AdditionalExtensions, SourceSystem, Type, outputfields, Computer
| sort by TimeGenerated
